In [1]:
import numpy as np
import pandas as pd

In [4]:
a = np.arange(5)    # a为一维数组，5个元素
b = np.arange(5,10) # b为一维数组,4个元素
ar1 = np.hstack((a,b))  # 注意:((a,b))，这里形状可以不一样
ar2 = np.vstack((a,b))
print(a,a.shape)
print(b,b.shape)
print(ar1,ar1.shape)
print(ar2,ar2.shape)

[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
