In [49]:
# Series 数据结构
# Series 是带有标签的一维数组，可以保存任何数据类型（整数，字符串，浮点数，Python对象等）,轴标签统称为索引

import numpy as np
import pandas as pd  
# 导入numpy、pandas模块

ar = np.random.rand(5)
print(ar,type(ar))

s = pd.Series(ar,index = list('abcde'))
print(s)
print(type(s))
           
# 查看数据、数据类"型


[0.94055689 0.7833975  0.16826444 0.94659673 0.73903187] <class 'numpy.ndarray'>
a    0.940557
b    0.783398
c    0.168264
d    0.946597
e    0.739032
dtype: float64
<class 'pandas.core.series.Series'>


In [48]:
print(s.index,type(s.index))
print('--------------------------\n')
print(s.values,type(s.values))
print(list(s.index))
print(list(s.values))

# .index查看series索引，类型为rangeindex
# .values查看series值，类型是ndarray

# 核心：series相比于ndarray，是一个自带索引index的数组 → 一维数组 + 对应索引
# 所以当只看series的值的时候，就是一个ndarray
# series和ndarray较相似，索引切片功能差别不大
# series和dict相比，series更像一个有顺序的字典（dict本身不存在顺序），其索引原理与字典相似（一个用key，一个用index）

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object') <class 'pandas.core.indexes.base.Index'>
--------------------------

['0.7559339692000479' '0.34345216245680654' '0.43979289108061737'
 '0.9648517499064465' '0.8335731353079258' '0.11740478143446831'
 '0.44390374413000233' '0.8137653563695089' '0.7435726301828988'
 '0.8825251789762238'] <class 'numpy.ndarray'>
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
['0.7559339692000479', '0.34345216245680654', '0.43979289108061737', '0.9648517499064465', '0.8335731353079258', '0.11740478143446831', '0.44390374413000233', '0.8137653563695089', '0.7435726301828988', '0.8825251789762238']


In [46]:
# Series 创建方法一：由字典创建，字典的key就是index，values就是values

dic = {'a':1 ,'b':2 , 'c':3, '4':4, '5':5,'a':3}
s = pd.Series(dic)
print(s)
# 注意：key肯定是字符串，假如values类型不止一个会怎么样？ → dic = {'a':1 ,'b':'hello' , 'c':3, '4':4, '5':5}

a    3
b    2
c    3
4    4
5    5
dtype: int64


In [53]:
arr = np.random.rand(10)
s = pd.Series(arr, index=list('abcdefghij'))
print(s)

a    0.650632
b    0.194724
c    0.446852
d    0.458729
e    0.582743
f    0.605649
g    0.621676
h    0.606938
i    0.196568
j    0.118127
dtype: float64


In [58]:
arr = np.random.randn(10)
s = pd.Series(arr, index=list('abcdefghij'))
print(s)

a   -0.697279
b    0.866233
c   -3.229064
d   -1.722464
e    0.504170
f   -1.301260
g   -0.674906
h    0.263877
i    0.891913
j    0.397767
dtype: float64


In [ ]:
????????????????????????????????????????????????

In [55]:
# 位置下标，类似序列

s = pd.Series(np.random.rand(5))
print(s)
print(s[0],type(s[0]),s[0].dtype)
print(float(s[0]),type(float(s[0])))
#print(s[-1])
# 位置下标从0开始
# 输出结果为numpy.float格式，
# 可以通过float()函数转换为python float格式
# numpy.float与float占用字节不同
# s[-1]结果如何？

0    0.116609
1    0.953350
2    0.912686
3    0.576732
4    0.328873
dtype: float64
0.11660893529702332 <class 'numpy.float64'> float64
0.11660893529702332 <class 'float'>


In [84]:
# 标签索引

s = pd.Series(np.random.rand(5)*100, index = ['a','b','c','d','e'])
print(s)
print(s['a'],type(s['a']),s['a'].dtype)
# 方法类似下标索引，用[]表示，内写上index，注意index是字符串

sci = s[['a','b','e']]
print(sci,type(sci))
# 如果需要选择多个标签的值，用[[]]来表示（相当于[]中包含一个列表）
# 多标签索引结果是新的数组

a    93.451726
b    96.236492
c    65.066404
d    11.597612
e    89.918638
dtype: float64
93.4517264117418 <class 'numpy.float64'> float64
a    93.451726
b    96.236492
e    89.918638
dtype: float64 <class 'pandas.core.series.Series'>


In [87]:
ss = s.astype('int64')
ss

a    93
b    96
c    65
d    11
e    89
dtype: int64

In [65]:
a = np.random.random(4)
a

array([0.44190813, 0.52321575, 0.53539253, 0.62661955])

In [66]:
a.dtype

dtype('float64')

In [67]:
a.shape

(4,)

In [72]:
a.dtype = 'int32'
a

array([  196375234,  1071401017,  -193027919,  1071693358, -2116455695,
        1071718895,  1867527646,  1071910212])